title: Faraz Shaikh
livereload: true
collections:
  experiments:
    output: true
    order:
      - Sea Breeze/index.html
      - Planet Generator/index.html
  libraries:
    output: true
    order:
      - gl-Noise.md
      - CSM.md
      - three-noise.md
  apps:
    output: true
    order:
      - Terrain Builder.md
exclude:
  - "About.*"
host: 0.0.0.0
